import { PLAYER_CONFIG } from '../../player/PlayerConfig';
import type { EnemyDefinition } from '../EnemyTypes';

export const BADGER_AGGRESSIVE: EnemyDefinition = {
  id: 'badger_aggressive',
  displayName: 'Tunnel Badger',
  description: 'A mean burrower that slows prey before darting in with a venomous bite.',
  visualId: 'badger',
  tier: 1,
  maxHealth: 5,
  initiative: 5,
  mpPerTurn: 3,
  apPerTurn: 1,
  slashDefence: 7,
  pierceDefence: 8,
  crushDefence: 5,
  lightningDefence: 7,
  fireDefence: 4,
  coldDefence: 6,
  poisonDefence: 12,
  behavior: 'aggressive',
  moveSpeed: PLAYER_CONFIG.movementSpeed * 0.66,
  collisionRadiusTiles: 0.42,
  aggroRangeTiles: 5,
  leashRangeTiles: 9,
  lootTables: [
    { oneIn: 1, entries: [{ itemId: 'rawhide', weight: 1 }] },
    { oneIn: 3, entries: [{ itemId: 'herb', weight: 1 }] },
    { oneIn: 8, entries: [{ itemId: 'bone', weight: 1 }] },
  ],
  attacks: [
    {
      id: 'badger_claw',
      displayName: 'Claw',
      apCost: 1,
      minRangeTiles: 0,
      maxRangeTiles: 1,
      damage: 1,
      damageType: 'slash',
      hitChance: 9,
    },
    {
      id: 'badger_burrow_bite',
      displayName: 'Burrow Bite',
      apCost: 1,
      minRangeTiles: 1,
      maxRangeTiles: 3,
      damage: 2,
      damageType: 'poison',
      hitChance: 7,
      statusEffect: { kind: 'damage_over_time', turns: 2, value: 1 },
      telegraph: { pattern: 'target', warningDamageMultiplier: 0.5 },
      cooldownTurns: 2,
    },
  ],
};
