import { PLAYER_CONFIG } from '../../player/PlayerConfig';
import type { EnemyDefinition } from '../EnemyTypes';

export const BADGER_PASSIVE: EnemyDefinition = {
  id: 'badger_passive',
  displayName: 'Badger',
  description: 'A small burrower that would rather dig away than fight.',
  visualId: 'badger',
  tier: 1,
  maxHealth: 4,
  initiative: 7,
  mpPerTurn: 3,
  apPerTurn: 1,
  slashDefence: 7,
  pierceDefence: 8,
  crushDefence: 5,
  lightningDefence: 7,
  fireDefence: 4,
  coldDefence: 6,
  poisonDefence: 12,
  behavior: 'passive',
  aiProfile: 'defensive',
  moveSpeed: PLAYER_CONFIG.movementSpeed * 0.60,
  collisionRadiusTiles: 0.42,
  aggroRangeTiles: 0,
  leashRangeTiles: 7,
  lootTables: [
    { oneIn: 1, entries: [{ itemId: 'rawhide', weight: 1 }] },
    { oneIn: 4, entries: [{ itemId: 'herb', weight: 1 }] },
  ],
  attacks: [
    {
      id: 'badger_nip',
      displayName: 'Nip',
      apCost: 1,
      minRangeTiles: 0,
      maxRangeTiles: 1,
      damage: 1,
      damageType: 'slash',
      hitChance: 8,
    },
    {
      id: 'badger_dirt_kick',
      displayName: 'Dirt Kick',
      apCost: 1,
      minRangeTiles: 0,
      maxRangeTiles: 1,
      damage: 1,
      damageType: 'crush',
      hitChance: 7,
      statusEffect: { kind: 'slowed', turns: 1, value: 1 },
      cooldownTurns: 2,
    },
  ],
};
