import { PLAYER_CONFIG } from '../../player/PlayerConfig';
import type { EnemyDefinition } from '../EnemyTypes';

export const BOAR_PASSIVE: EnemyDefinition = {
  id: 'boar_passive',
  displayName: 'Boar',
  description: 'A wary forager. It only fights when provoked or cornered.',
  visualId: 'boar',
  tier: 1,
  maxHealth: 6,
  initiative: 10,
  mpPerTurn: 2,
  apPerTurn: 1,
  slashDefence: 8,
  pierceDefence: 7,
  crushDefence: 10,
  lightningDefence: 7,
  fireDefence: 5,
  coldDefence: 8,
  poisonDefence: 9,
  behavior: 'passive',
  aiProfile: 'defensive',
  moveSpeed: PLAYER_CONFIG.movementSpeed * 0.50,
  collisionRadiusTiles: 0.45,
  aggroRangeTiles: 0,
  leashRangeTiles: 8,
  lootTables: [
    { oneIn: 1, entries: [{ itemId: 'rawhide', weight: 1 }] },
    { oneIn: 12, entries: [{ itemId: 'boarhide', weight: 1 }] },
  ],
  attacks: [
    {
      id: 'boar_tusk_jab',
      displayName: 'Tusk Jab',
      apCost: 1,
      minRangeTiles: 0,
      maxRangeTiles: 1,
      damage: 2,
      damageType: 'pierce',
      hitChance: 7,
    },
    {
      id: 'boar_shove',
      displayName: 'Shove',
      apCost: 1,
      minRangeTiles: 0,
      maxRangeTiles: 1,
      damage: 1,
      damageType: 'crush',
      hitChance: 7,
      forcedMovement: { kind: 'push', distance: 1 },
      cooldownTurns: 2,
    },
  ],
};
