import { PLAYER_CONFIG } from '../../player/PlayerConfig';
import type { EnemyDefinition } from '../EnemyTypes';

export const BOAR_AGGRESSIVE: EnemyDefinition = {
  id: 'boar_aggressive',
  displayName: 'Bristle Boar',
  description: 'A stocky island boar that commits hard to straight-line charges.',
  visualId: 'boar',
  tier: 1,
  maxHealth: 7,
  initiative: 8,
  mpPerTurn: 2,
  apPerTurn: 1,
  slashDefence: 8,
  pierceDefence: 7,
  crushDefence: 11,
  lightningDefence: 7,
  fireDefence: 5,
  coldDefence: 8,
  poisonDefence: 9,
  behavior: 'aggressive',
  moveSpeed: PLAYER_CONFIG.movementSpeed * 0.58,
  collisionRadiusTiles: 0.45,
  aggroRangeTiles: 6,
  leashRangeTiles: 10,
  lootTables: [
    { oneIn: 1, entries: [{ itemId: 'rawhide', weight: 1 }] },
    { oneIn: 8, entries: [{ itemId: 'boarhide', weight: 1 }] },
    { oneIn: 8, entries: [{ itemId: 'bone', weight: 1 }] },
  ],
  attacks: [
    {
      id: 'boar_gore',
      displayName: 'Gore',
      apCost: 1,
      minRangeTiles: 0,
      maxRangeTiles: 1,
      damage: 2,
      damageType: 'pierce',
      hitChance: 8,
    },
    {
      id: 'boar_charge',
      displayName: 'Charge',
      apCost: 1,
      minRangeTiles: 2,
      maxRangeTiles: 4,
      damage: 3,
      damageType: 'crush',
      hitChance: 7,
      telegraph: { pattern: 'line', length: 4, warningDamageMultiplier: 0.5 },
      forcedMovement: { kind: 'push', distance: 1 },
      cooldownTurns: 2,
    },
  ],
};
