import { PLAYER_CONFIG } from '../../player/PlayerConfig';
import type { EnemyDefinition } from '../EnemyTypes';

export const BOAR_BOSS: EnemyDefinition = {
  id: 'boar_boss',
  displayName: 'Tuskuss',
  description: 'The scarred alpha of the thicket. Tuskuss breaks cover, stone, and careless challengers.',
  visualId: 'boar',
  visualTint: 0x9f5f36,
  visualScaleMultiplier: 1.55,
  footprintSize: 2,
  tier: 2,
  maxHealth: 30,
  initiative: 9,
  mpPerTurn: 2,
  apPerTurn: 1,
  slashDefence: 12,
  pierceDefence: 10,
  crushDefence: 15,
  lightningDefence: 9,
  fireDefence: 7,
  coldDefence: 9,
  poisonDefence: 14,
  behavior: 'aggressive',
  aiProfile: 'charger',
  enrage: {
    hpRatio: 0.35,
    apBonus: 1,
    hitChanceMultiplier: 0.65,
    damageMultiplier: 1.3,
  },
  earthPillarPhase: {
    id: 'rootbound_shell',
    hpRatio: 0.6,
    pillarCount: 4,
    pillarHp: 6,
    healPerTurn: 3,
    magicImmuneWhileActive: true,
  },
  moveSpeed: PLAYER_CONFIG.movementSpeed * 0.56,
  collisionRadiusTiles: 0.95,
  aggroRangeTiles: 7,
  leashRangeTiles: 12,
  lootTables: [
    { oneIn: 1, entries: [{ itemId: 'rawhide', count: 3, weight: 1 }] },
    { oneIn: 1, entries: [{ itemId: 'boarhide', weight: 1 }] },
    { oneIn: 2, entries: [{ itemId: 'bone', count: 2, weight: 1 }] },
  ],
  attacks: [
    {
      id: 'tuskuss_tusk_slam',
      displayName: 'Tusk Slam',
      apCost: 1,
      minRangeTiles: 0,
      maxRangeTiles: 1,
      damage: 3,
      damageType: 'crush',
      hitChance: 9,
      forcedMovement: { kind: 'push', distance: 1 },
      staggerDamage: 3,
    },
    {
      id: 'tuskuss_rootbreaker_charge',
      displayName: 'Rootbreaker Charge',
      apCost: 1,
      minRangeTiles: 2,
      maxRangeTiles: 5,
      damage: 5,
      damageType: 'crush',
      hitChance: 8,
      telegraph: { pattern: 'line', length: 5, widthTiles: 2, warningDamageMultiplier: 0.45 },
      forcedMovement: { kind: 'push', distance: 2 },
      staggerDamage: 4,
      cooldownTurns: 2,
    },
    {
      id: 'tuskuss_bristle_quake',
      displayName: 'Bristle Quake',
      apCost: 1,
      minRangeTiles: 0,
      maxRangeTiles: 2,
      damage: 2,
      damageType: 'crush',
      hitChance: 8,
      telegraph: { pattern: 'ring', radius: 2, warningDamageMultiplier: 0.5 },
      statusEffect: { kind: 'slowed', turns: 1, value: 1 },
      cooldownTurns: 3,
    },
  ],
};
