import { PLAYER_CONFIG } from '../../player/PlayerConfig';
import type { EnemyDefinition } from '../EnemyTypes';

export const STAG_PASSIVE: EnemyDefinition = {
  id: 'stag_passive',
  displayName: 'Stag',
  description: 'A nervous grazing animal. It fights clumsily if trapped.',
  visualId: 'stag',
  tier: 1,
  maxHealth: 4,
  initiative: 9,
  mpPerTurn: 4,
  apPerTurn: 1,
  slashDefence: 6,
  pierceDefence: 6,
  crushDefence: 5,
  lightningDefence: 7,
  fireDefence: 4,
  coldDefence: 7,
  poisonDefence: 5,
  behavior: 'passive',
  aiProfile: 'defensive',
  moveSpeed: PLAYER_CONFIG.movementSpeed * 0.68,
  collisionRadiusTiles: 0.45,
  aggroRangeTiles: 0,
  leashRangeTiles: 9,
  lootTables: [
    { oneIn: 1, entries: [{ itemId: 'rawhide', weight: 1 }] },
  ],
  attacks: [
    {
      id: 'stag_kick',
      displayName: 'Kick',
      apCost: 1,
      minRangeTiles: 0,
      maxRangeTiles: 1,
      damage: 1,
      damageType: 'crush',
      hitChance: 7,
      forcedMovement: { kind: 'push', distance: 1 },
    },
    {
      id: 'stag_startle',
      displayName: 'Startle',
      apCost: 1,
      minRangeTiles: 0,
      maxRangeTiles: 1,
      damage: 1,
      damageType: 'crush',
      hitChance: 6,
      statusEffect: { kind: 'slowed', turns: 1, value: 1 },
      cooldownTurns: 3,
    },
  ],
};
