import { PLAYER_CONFIG } from '../../player/PlayerConfig';
import type { EnemyDefinition } from '../EnemyTypes';

export const STAG_AGGRESSIVE: EnemyDefinition = {
  id: 'stag_aggressive',
  displayName: 'Startled Stag',
  description: 'A panicked herd animal. Weak alone, dangerous when several bolt together.',
  visualId: 'stag',
  tier: 1,
  maxHealth: 4,
  initiative: 6,
  mpPerTurn: 4,
  apPerTurn: 1,
  slashDefence: 6,
  pierceDefence: 6,
  crushDefence: 5,
  lightningDefence: 7,
  fireDefence: 4,
  coldDefence: 7,
  poisonDefence: 5,
  behavior: 'aggressive',
  moveSpeed: PLAYER_CONFIG.movementSpeed * 0.74,
  collisionRadiusTiles: 0.45,
  aggroRangeTiles: 5,
  leashRangeTiles: 12,
  lootTables: [
    { oneIn: 1, entries: [{ itemId: 'rawhide', weight: 1 }] },
    { oneIn: 6, entries: [{ itemId: 'bone', weight: 1 }] },
  ],
  attacks: [
    {
      id: 'stag_kick',
      displayName: 'Kick',
      apCost: 1,
      minRangeTiles: 0,
      maxRangeTiles: 1,
      damage: 1,
      damageType: 'crush',
      hitChance: 8,
      forcedMovement: { kind: 'push', distance: 1 },
    },
    {
      id: 'stag_panic_bolt',
      displayName: 'Panic Bolt',
      apCost: 1,
      minRangeTiles: 2,
      maxRangeTiles: 4,
      damage: 2,
      damageType: 'crush',
      hitChance: 6,
      telegraph: { pattern: 'line', length: 4, warningDamageMultiplier: 0.5 },
      forcedMovement: { kind: 'push', distance: 1 },
      cooldownTurns: 3,
    },
  ],
};
