import { PLAYER_CONFIG } from '../../player/PlayerConfig';
import type { EnemyDefinition } from '../EnemyTypes';

export const TRAINING_WRETCH: EnemyDefinition = {
  id: 'training_wretch',
  displayName: 'Training Wretch',
  tier: 1,
  maxHealth: 5,
  initiative: 10,
  mpPerTurn: 2,
  apPerTurn: 1,
  slashDefence: 0,
  pierceDefence: 0,
  crushDefence: 0,
  lightningDefence: 0,
  fireDefence: 0,
  coldDefence: 0,
  poisonDefence: 0,
  moveSpeed: PLAYER_CONFIG.movementSpeed * 0.42,
  collisionRadiusTiles: 0.65,
  aggroRangeTiles: 9,
  leashRangeTiles: 11,
  lootTables: [
    { oneIn: 1, entries: [{ itemId: 'wood',  count: 2, weight: 1 }] },
    { oneIn: 2, entries: [{ itemId: 'stone',         weight: 1 }] },
    { oneIn: 3, entries: [{ itemId: 'herb',          weight: 1 }] },
  ],
  attacks: [
    {
      id: 'wretch_swipe',
      displayName: 'Swipe',
      apCost: 1,
      minRangeTiles: 0,
      maxRangeTiles: 1,
      damage: 2,
      damageType: 'slash',
      hitChance: 7,
    },
    {
      id: 'wretch_slam',
      displayName: 'Slam',
      apCost: 1,
      minRangeTiles: 0,
      maxRangeTiles: 1,
      damage: 3,
      damageType: 'crush',
      hitChance: 6,
      statusEffect: { kind: 'stunned', turns: 1, value: 0 },
      cooldownTurns: 3,
    },
  ],
};
