import { PLAYER_CONFIG } from '../../player/PlayerConfig';
import type { EnemyDefinition } from '../EnemyTypes';

export const WOLF_AGGRESSIVE: EnemyDefinition = {
  id: 'wolf_aggressive',
  displayName: 'Wolf',
  tier: 1,
  maxHealth: 5,
  initiative: 6,
  mpPerTurn: 3,
  apPerTurn: 1,
  slashDefence: 28,
  pierceDefence: 24,
  crushDefence: 34,
  lightningDefence: 55,
  fireDefence: 8,
  coldDefence: 22,
  poisonDefence: 18,
  behavior: 'aggressive',
  moveSpeed: PLAYER_CONFIG.movementSpeed * 0.70,
  collisionRadiusTiles: 0.55,
  aggroRangeTiles: 8,
  leashRangeTiles: 14,
  lootTables: [
    {
      oneIn: 1,
      entries: [
        { itemId: 'wolf_pelt_torn',    weight: 9 },
        { itemId: 'wolf_pelt_healthy', weight: 1 },
      ],
    },
    { oneIn: 10, entries: [{ itemId: 'bone', weight: 1 }] },
  ],
  attacks: [
    {
      id: 'wolf_bite',
      displayName: 'Bite',
      apCost: 1,
      minRangeTiles: 0,
      maxRangeTiles: 1,
      damage: 2,
      damageType: 'pierce',
      hitChance: 80,
      statusEffect: { kind: 'bleeding', turns: 2, value: 1 },
    },
    {
      id: 'wolf_pounce',
      displayName: 'Pounce',
      apCost: 1,
      minRangeTiles: 2,
      maxRangeTiles: 5,
      damage: 3,
      damageType: 'crush',
      hitChance: 85,
      statusEffect: { kind: 'bleeding', turns: 2, value: 1 },
      telegraph: { pattern: 'target_plus_adjacent', warningDamageMultiplier: 0.5 },
      forcedMovement: { kind: 'push', distance: 1 },
      cooldownTurns: 2,
    },
  ],
};
