import type { ItemDefinition } from '../ItemTypes';

export const MATERIAL_ITEMS: ItemDefinition[] = [
  {
    id: 'wood',
    name: 'Driftwood',
    examine: 'Dry wood gathered from shore or fallen brush.',
    icon: '🪵',
    category: 'material',
    stackable: false,
    weight: 0.5,
    value: 1,
  },
  {
    id: 'stone',
    name: 'Stone',
    examine: 'A rough stone that can strike sparks or support simple crafting.',
    icon: '🪨',
    category: 'material',
    stackable: false,
    weight: 1.0,
    value: 1,
  },
  {
    id: 'herb',
    name: 'Herb',
    examine: 'A gathered herb that can be brewed over an active fire.',
    icon: '🌿',
    category: 'material',
    stackable: false,
    weight: 0.1,
    value: 2,
  },
  {
    id: 'bone',
    name: 'Bone',
    examine: 'A gnawed bone — material for tools or fuel.',
    icon: '🦴',
    category: 'material',
    stackable: false,
    weight: 0.3,
    value: 1,
  },
  {
    id: 'wolf_pelt_healthy',
    name: 'Wolf Pelt',
    examine: 'Intact wolf fur. Rare — worth keeping for serious crafting.',
    icon: '🐺',
    category: 'material',
    stackable: false,
    weight: 0.8,
    value: 12,
  },
  {
    id: 'wolf_pelt_torn',
    name: 'Torn Pelt',
    examine: 'Damaged wolf fur. Less prized but still useful in a pinch.',
    icon: '🪶',
    category: 'material',
    stackable: false,
    weight: 0.6,
    value: 4,
  },
];
