import type { ItemDefinition } from './ItemTypes';

export const ITEM_DEFINITIONS: ItemDefinition[] = [
  {
    id: 'wood',
    displayName: 'Driftwood',
    description: 'Dry wood gathered from shore or fallen brush.',
    category: 'resource',
    stackable: true,
    useMode: 'none',
  },
  {
    id: 'stone',
    displayName: 'Stone',
    description: 'A rough stone that can strike sparks or support simple crafting.',
    category: 'resource',
    stackable: true,
    useMode: 'none',
  },
  {
    id: 'herb',
    displayName: 'Herb',
    description: 'A gathered herb that can be brewed over an active fire.',
    category: 'resource',
    stackable: true,
    useMode: 'none',
  },
  {
    id: 'firestarter_set',
    displayName: 'Firestarter Set',
    description: 'A dry bundle of kindling tied for quick placement.',
    category: 'crafted',
    stackable: true,
    useMode: 'place',
    placementRules: {
      allowedSpaceTypes: ['personal_island', 'open_world'],
      mustBeWalkable: true,
      mustNotBeBlocked: true,
      durationMs: 45_000,
    },
    placementObjectDefinitionId: 'placed_firestarter_set',
  },
  {
    id: 'wooden_marker',
    displayName: 'Wooden Marker',
    description: 'A simple carved marker for trails or camp notes.',
    category: 'crafted',
    stackable: true,
    useMode: 'none',
  },
  {
    id: 'camp_supplies',
    displayName: 'Camp Supplies',
    description: 'A bundled pack of rough camp essentials ready to hand off.',
    category: 'crafted',
    stackable: true,
    useMode: 'none',
  },
  {
    id: 'warm_tea',
    displayName: 'Warm Tea',
    description: 'A simple hot drink brewed over a campfire.',
    category: 'consumable',
    stackable: true,
    useMode: 'consume',
    consumableEffectId: 'warm_tea_warmth',
    consumeMessage: 'You drink warm tea.',
  },
];
