import type { CompanionDefinition } from './CompanionTypes';

const DEFINITIONS: Record<string, CompanionDefinition> = {
  wolf: {
    id: 'wolf',
    displayName: 'Wolf',
    maxHp: 2,
    attackPower: 1,
    slashDefence: 0,
    pierceDefence: 0,
    crushDefence: 0,
    lightningDefence: 0,
    fireDefence: 0,
    coldDefence: 0,
    poisonDefence: 0,
    attackRangeTiles: 5,
    initiative: 7,
    apPerTurn: 1,
    mpPerTurn: 3,
    staggerThreshold: 3,
    attacks: [
      {
        id: 'jump',
        displayName: 'Jump',
        apCost: 1,
        minRangeTiles: 2,
        maxRangeTiles: 5,
        damage: 1,
        damageType: 'crush',
        hitChance: 8,
        telegraph: { pattern: 'target_plus_adjacent', warningDamageMultiplier: 0.5 },
        forcedMovement: { kind: 'push', distance: 1 },
        cooldownTurns: 2,
      },
      {
        id: 'bite',
        displayName: 'Bite',
        apCost: 1,
        minRangeTiles: 1,
        maxRangeTiles: 1,
        damage: 1,
        damageType: 'pierce',
        hitChance: 10,
      },
    ],
    maxDurability: 30,
  },

  bronze_golem: {
    id: 'bronze_golem',
    displayName: 'Bronze Golem',
    maxHp: 30,
    attackPower: 4,
    slashDefence: 12,
    pierceDefence: 12,
    crushDefence: 8,
    lightningDefence: 4,
    fireDefence: 6,
    coldDefence: 2,
    poisonDefence: 10,
    attackRangeTiles: 1,
    initiative: 12,
    apPerTurn: 1,
    mpPerTurn: 2,
    staggerThreshold: 14,
    attacks: [
      {
        id: 'slam',
        displayName: 'Slam',
        apCost: 1,
        minRangeTiles: 0,
        maxRangeTiles: 1,
        damage: 4,
        damageType: 'crush',
        hitChance: 8,
        staggerDamage: 4,
      },
    ],
    maxDurability: 20,
  },

  imp: {
    id: 'imp',
    displayName: 'Imp',
    maxHp: 12,
    attackPower: 3,
    slashDefence: 1,
    pierceDefence: 1,
    crushDefence: 1,
    lightningDefence: 0,
    fireDefence: 3,
    coldDefence: 0,
    poisonDefence: 2,
    attackRangeTiles: 2,
    initiative: 5,
    apPerTurn: 1,
    mpPerTurn: 3,
    staggerThreshold: 6,
    attacks: [
      {
        id: 'claw',
        displayName: 'Claw',
        apCost: 1,
        minRangeTiles: 0,
        maxRangeTiles: 2,
        damage: 3,
        damageType: 'slash',
        hitChance: 9,
        statusEffect: { kind: 'bleeding', turns: 2, value: 1 },
      },
    ],
    maxDurability: 25,
  },
};

export function getCompanionDefinition(id: string): CompanionDefinition | undefined {
  return DEFINITIONS[id];
}

export const ALL_COMPANION_DEFINITIONS: CompanionDefinition[] = Object.values(DEFINITIONS);
