export type SfxEventId =
  | 'menu_open'
  | 'menu_select'
  | 'menu_confirm'
  | 'menu_cancel'
  | 'ui_tab_open'
  | 'ui_tab_close'
  | 'ui_button'
  | 'gather_start'
  | 'gather_success'
  | 'craft_start'
  | 'craft_success'
  | 'craft_failed'
  | 'action_cancelled'
  | 'item_placed'
  | 'fire_lit'
  | 'tea_brewed'
  | 'tea_consumed'
  | 'footstep_walk'
  | 'footstep_run'
  | 'combat_start'
  | 'dodge'
  | 'player_attack'
  | 'guard_block'
  | 'guard_break'
  | 'combat_hit'
  | 'combat_miss'
  | 'enemy_down'
  | 'contract_accepted'
  | 'contract_completed'
  | 'xp_gain'
  | 'invalid_action'
  | 'map_transition';

export type SfxEventPayload = {
  id: SfxEventId;
};
