export const PROTOTYPE_SCALE = {
  tileWidth: 64,
  tileHeight: 32,
  playerVisualScale: 2,
  mapWidth: 180,
  mapHeight: 180,
  terrainChunkSize: 16,
  terrainChunkVisibleRadius: 1,
  terrainChunkRetainRadius: 3,
  terrainChunkBleedTiles: 1,
  terrainChunkGroundBuildBudgetPerFrame: 96,
  terrainChunkGridBuildBudgetPerFrame: 64,
  debugOverlayBannerRefreshMs: 120,
  debugOverlayDetailRefreshMs: 200,
} as const;
